### ISSUE TITLE
:,D

### ISSUE THREAD

**Issue by ghost** [majovec/JumpLeague#1]
Jde videt ze neumis uploadnout slozku na github protože v kazde mas nejaky unknown soubor 👍  :DD

**Comment by majovec** [comment]
coo ti je do toho ty mrdko jl od blua jem em dval z nudy  ted zales k mame do pici

**Comment by ghost** [comment]
a to tam neumis pretahnout slozku??? :D

**Comment by majovec** [comment]
Nemám čas na to srat se tu s detma tak ze blokace měj se prcku
